# Generated by Django 5.2.5 on 2025-08-23 04:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_username",
                    models.CharField(
                        blank=True,
                        max_length=39,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid GitHub username format.",
                                regex="^[a-zA-Z0-9](?:[a-zA-Z0-9]|-(?=[a-zA-Z0-9])){0,38}$",
                            )
                        ],
                    ),
                ),
                (
                    "leetcode_username",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="LeetCode username can only contain letters, numbers, hyphens, and underscores.",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                ("total_score", models.IntegerField(default=0)),
                ("github_score", models.IntegerField(default=0)),
                ("leetcode_score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-total_score", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("GitHub", "GitHub"), ("LeetCode", "LeetCode")],
                        max_length=50,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="leaderboardapp.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "platform")},
            },
        ),
    ]
