# Generated by Django 5.2.5 on 2025-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "leetcode_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
